### ISSUE TITLE
hardcoded module ids

### ISSUE THREAD

**Issue by danmarsden** [Celumproject/moodle-mod_domoscio#26]
this is really fragile:
https://github.com/Celumproject/moodle-mod_domoscio/blob/master/domoscio/mod_form.php#L105

you can't really rely on those ids even if most fresh installs work it's possible for the numbers to be different in certain circumstances.

**Comment by fearcraftor** [comment]
Fixed in latest commit https://github.com/Celumproject/moodle-mod_domoscio/commit/d3ddb1b7269b570ebdf61cd3917f383de10d0ee0

Now queries aren't based upon module id anymore but on module name string

Fixed also something similar dealing with lesson page types that are retrived with get_idstring function

**Comment by danmarsden** [comment]
much better solution there - nice!

**Comment by mudrd8mz** [comment]
So should this be closed now?

**Comment by fearcraftor** [comment]
If everybody is satisfied with that, yes indeed
