### ISSUE TITLE
player.php allows non-authenticated access to all SCORM packages

### ISSUE THREAD

**Issue by danmarsden** [Celumproject/moodle-mod_domoscio#9]
the custom player.php file seems to be a copy of the mod/scorm/player.php but removes the login checks which appears to grant anonymous access to all SCORM packages on the site. This MUST be fixed before the plugin can be approved in the moodle.org plugins db.

It also seems quite strange to re-implement the player.php to lauch scorm packages. it would be better to call the scorm player page directly if possible - if it is not possible it should be very clear in your documentation why you have re-implemented the player.php page and what differences it has compared with launching directly from the standard mod/scorm code.

**Comment by fearcraftor** [comment]
login check reimplemented, see commit https://github.com/Celumproject/moodle-mod_domoscio/commit/5b37f52294edce9b0636039cd94879a180245060

We needed to slightly modifiy player.php as the original didn't fit well the workflow of our plugin, and also get control on new attempts, which is absolutely necessary for our plugin to work.

thanks

Florent
Domoscio

**Comment by danmarsden** [comment]
You need to clarify this further - I'm not convinced yet that you should
implement your own player.php file. You should include documention in a
readme file or at the least some specific comments within the player.php
file that explains exactly why it is required and how it differs from the
core mod/scorm/player.php file.

Dan

**Comment by fearcraftor** [comment]
Hi Dan,

here are some reasons why we use modified player.php : 

Context : We developed the plugin with the goal to provide student the ability to do trainings and view results and stats in a unified way. So it's obvious that all student activities must be done into the plugin.

Basically, our plugin search for all SCOes linked to the notion review, choose one randomly to show to student, and retrive result send by the included activity.

So it is fundamental to include player.php into our doquiz.php view : our view pre-process the SCO display as explained above, and provide Validate and Terminate button which redirect to our results.php view which retrive result.

Here are problems encountered by calling directly player.php from SCORM mod folder:

- player.php require variables such as scoid, scormid, mode, etc... passing these variables to the included player.php require the use of $_POST / $_GET which is forbidden by Moodle guidelines.

- many conflicts as the doquiz and player views calls page render functions (to display heading, header, footer, etc...) -> we need to delete call in the player.php and only calling on doquiz.php

- our plugin absolutely need a new attempt to be written in database in order to retrive SCORM results. The way SCORM mod manage new attempts in moodle don't fit our objectives : 
the scorm check mode function search for a SCORM element called 'cmi.core.lesson_status' to determine if there's a new attempt or not. This element isn't send by all SCORM packages and we had problems with that. So we re included this function in our librairies in order to allow a wide range of SCORM packages working with our plugin.

I'll attach comments in our player file about everything listed above

Florent
Domoscio

**Comment by danmarsden** [comment]
To be honest, I'm still not convinced. I hadn't realised you were embedding your player.php directly into another page as I did not perform a complete review, now that I see this I don't like it much.

With my "SCORM Maintainer" hat on I couldn't personally approve the plugin within the plugins db as i do not believe the design is safe and it sounds like it will abuse the SCORM standards by providing different handling around lesson_status and attempts.

The code still needs further work to comply with our coding standards but IMO the overall design needs more work.

Note: I do not make the final decisions around approval/rejection of plugins within the database - David Mudrak @mudrd8mz has that responsibility.

**Comment by danmarsden** [comment]
a better design would be to use the existing player.php file within scorm but embed it within a frame on your page to allow you to add other elements - you can then pass the param display=popup in the player.php url to strip out the moodle header/footers.

**Comment by fearcraftor** [comment]
Thank you for your advice, we succeeded to include original player.php into a iframe in our doquiz view, and it works pretty good, even if there's some params to set in SCORM admin to have the best experience (collapse TOC by default for example).
We revamped the SQL resquest to retrive latest student attempt even if there's still a bug with scorm_check_mode if SCORM package don't send the right runtime element.

See commit here : https://github.com/Celumproject/moodle-mod_domoscio/commit/289f09719ebc69fcffbd7512ab4b6d2161b6e13a

Regards
Florent
Domoscio

**Comment by danmarsden** [comment]
that looks much safer - once you have addressed the other issues please update the version in the moodle.org plugins db and flag it as ready for the plugins team to take another look.
